In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from scipy import stats

In [11]:
# load data
sales = pd.read_csv("../../ML Data & Script/kc_house_data.csv")
sales.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [12]:
# split data into training and testing
from sklearn.model_selection import train_test_split
target = sales['price']
X_train, X_test, y_train, y_test = train_test_split(sales, target, test_size=0.2, random_state=0)

In [20]:
features = ['sqft_living', 'bedrooms', 'bathrooms']
# use sklearn
from sklearn.linear_model import LinearRegression
model_one = LinearRegression()
model_one.fit(X_train[example_features],y_train)
print("cofficents: ", model_one.coef_)
print("intercept: ", model_one.intercept_)
print("R2", model_one.score(X_train[example_features],y_train))

cofficents:  [   313.17055038 -56754.66651422   6887.71910816]
intercept:  67512.01513813145
0.5090198210347912

In [19]:
# use statsmodels
import statsmodels.formula.api as smf
import statsmodels.api as sm
# An intercept is not included by default and should be added by the user
X_train = sm.add_constant(X_train[example_features])
model_two = smf.OLS(y_train, X_train).fit()
print(model_two.summary())
print("\n pvalues \n")
print(model_two.pvalues)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.509
Model:                            OLS   Adj. R-squared:                  0.509
Method:                 Least Squares   F-statistic:                     5974.
Date:                Mon, 17 Dec 2018   Prob (F-statistic):               0.00
Time:                        00:09:35   Log-Likelihood:            -2.4018e+05
No. Observations:               17290   AIC:                         4.804e+05
Df Residuals:                   17286   BIC:                         4.804e+05
Df Model:                           3
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const        6.751e+04   7739.284      8.723      0.000    5.23e+04    8.27e+04
sqft_living   313.1706      3.473     90.166      0.000     306.363     319.979
bedrooms    -5.675e+04   2610.241    -21.743      0.000   -6.19e+04   -5.16e+04
bathrooms    6887.7191   3956.603      1.741      0.082    -867.624    1.46e+04
==============================================================================
Omnibus:                    11730.325   Durbin-Watson:                   2.020
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           424556.267
Skew:                           2.778   Prob(JB):                         0.00
Kurtosis:                      26.631   Cond. No.                     9.22e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.22e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

 pvalues

const           2.944090e-18
sqft_living     0.000000e+00
bedrooms       1.947456e-103
bathrooms       8.173358e-02
dtype: float64

In [ ]:
# make predictions
example_predictions = model1.predict(train_data)
print example_predictions[0] # should be 271789.505878